print("Please fill in the blanks below")
print("_______'s favorite subject in school is _________")
name = input("What is name? ")
subject = input("What is subject? ")
print(f"{name}'s favorite subject in school is {subject}.'")